import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Providers } from "@/redux/Provider";
// import { NavBarComponent } from "@/components/Navbar";
import MainComponent from "@/components/Navbar/Main";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "clients",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          {/* <NavBarComponent>{children}</NavBarComponent> */}
          <MainComponent>{children}</MainComponent>
        </Providers>
      </body>
      {/* <Toaster richColors closeButton position="top-right" /> */}
    </html>
  );
}
